# (IIP314W) Optimización Aplicada a Negocios
## Ayudantía 7: Simplex con Restricciones ≥ — Método Gran M

---

**Profesor:** Ing. Rodrigo Trigo Vilches  
**Ayudante:** Lic. Vicente Ramírez Almonacid  
**Fecha:** 22 de Abril, 2026  
**Universidad del Desarrollo**

---

## 1. Teoría: ¿Por qué las restricciones ≥ complican el Simplex?

### 1.1 Repaso: Forma Estándar con Restricciones ≤

Cuando todas las restricciones son del tipo $\leq$, la conversión a forma estándar es directa: se agrega una **variable de holgura** $s_i \geq 0$ a cada restricción:

$$a_1 x_1 + a_2 x_2 \leq b \quad \xrightarrow{+s_i} \quad a_1 x_1 + a_2 x_2 + s_i = b$$

La colección de holguras forma automáticamente una **base inicial factible**: $B = I$ (identidad), con $x_B = b \geq 0$.

### 1.2 El Problema con Restricciones ≥

Cuando una restricción es del tipo $\geq$, se **resta** una variable de excedente (surplus) $e_i \geq 0$:

$$a_1 x_1 + a_2 x_2 \geq b \quad \xrightarrow{-e_i} \quad a_1 x_1 + a_2 x_2 - e_i = b$$

El problema: la columna de $e_i$ es $-e_i$ en la restricción, con coeficiente $-1$. Si usáramos $\{e_i\}$ como base, tendríamos $x_B = B^{-1}b$ donde la columna de $e_i$ tiene $-1$, lo que da **$x_B < 0$** para $b > 0$ — infactible.

> **En resumen:** las variables de excedente tienen signo negativo y no pueden formar una base factible por sí solas.

### 1.3 Solución: Variables Artificiales y el Método de la Gran M

Para cada restricción $\geq$ se agrega una **variable artificial** $a_i \geq 0$ que sí tiene coeficiente $+1$ (forma la identidad) y **permite arrancar** el algoritmo con una SBF:

$$a_1 x_1 + a_2 x_2 - e_i + a_i = b$$

Sin embargo, la variable artificial es **ficticia**: no pertenece al problema real. Para forzar que $a_i = 0$ en la solución óptima, se penaliza fuertemente su presencia en la función objetivo:

$$\text{Maximización:} \quad \max \; z = c^\top x - M \cdot a_i \qquad (M \gg 0)$$

Si $a_i > 0$ al final, el problema es **infactible** (no existe solución que satisfaga todas las restricciones).

### 1.4 Tabla Resumen de Variables

| Tipo de restricción | Variable que se agrega | Nombre | Coef. en obj. | ¿Forma base inicial? |
|:---:|:---:|:---:|:---:|:---:|
| $\leq$ | $+s_i$ | Holgura (slack) | $0$ | Sí ✓ |
| $\geq$ | $-e_i$ | Excedente (surplus) | $0$ | No ✗ |
| $\geq$ | $+a_i$ | Artificial | $-M$ (max) / $+M$ (min) | Sí ✓ (pero ficticia) |

### 1.5 Ajuste del Tableau Inicial

Al iniciar el tableau con artificiales en la base, la fila de costos reducidos (CR) **no** puede mostrar directamente $-c$ para los coeficientes de los artificiales — deben eliminarse de la fila objetivo mediante operaciones de fila, igual que en el método de Gauss-Jordan.

$$\text{CR}_{\text{nuevo}} = \text{CR}_{\text{inicial}} - M \cdot R_{a_i}$$

Esto garantiza que la columna de $a_i$ tenga cero en la fila CR (condición de variable básica).

---

## 2. Ejercicio: Simplex Tableau (Gran M)

### Contexto de Negocio

**EcoPanel S.A.** es una empresa que fabrica paneles solares para el mercado residencial. Su catálogo incluye dos modelos:

- **Panel Estándar** ($x_1$): diseño convencional, utilidad neta de **\$5 por unidad**.
- **Panel Premium** ($x_2$): mayor eficiencia energética, utilidad neta de **\$6 por unidad**.

La planta opera bajo las siguientes condiciones semanales:

| Recurso / Condición | Panel Estándar ($x_1$) | Panel Premium ($x_2$) | Límite |
|:---|:---:|:---:|:---:|
| Fibra de vidrio (m²) | $1$ | $1$ | $\leq 6$ m² |
| Horas de montaje (hrs) | $2$ | $1$ | $\leq 10$ hrs |
| Contrato garantizado (unid.) | $1$ | $0$ | $\geq 2$ unidades |
| **Utilidad (\$/unidad)** | **\$5** | **\$6** | — |

La empresa tiene un **contrato de largo plazo** con un cliente industrial que exige al menos **2 paneles estándar por semana**. Esta restricción de mínimo es la que introduce la complejidad del método Gran M.

### Formulación del Problema

$$\max \quad z = 5x_1 + 6x_2$$

$$\text{s.a.} \quad \begin{cases}
x_1 + x_2 \leq 6 & \text{(fibra de vidrio)} \\
2x_1 + x_2 \leq 10 & \text{(horas de montaje)} \\
x_1 \geq 2 & \text{(contrato mínimo)} \\
x_1,\, x_2 \geq 0
\end{cases}$$

### Forma Estándar

Identifique las variables auxiliares necesarias y escriba la forma estándar del problema:

- $s_1 \geq 0$: holgura de la restricción de fibra de vidrio ($\leq$).
- $s_2 \geq 0$: holgura de la restricción de horas de montaje ($\leq$).
- $e_3 \geq 0$: excedente de la restricción de contrato mínimo ($\geq$).
- $a_3 \geq 0$: artificial de la restricción de contrato mínimo ($\geq$).

$$\max \quad z = 5x_1 + 6x_2 + 0 s_1 + 0 s_2 + 0 e_3 - M a_3$$

$$\text{s.a.} \quad \begin{cases}
x_1 + x_2 + s_1 = 6 \\
2x_1 + x_2 + s_2 = 10 \\
x_1 - e_3 + a_3 = 2 \\
x_1, x_2, s_1, s_2, e_3, a_3 \geq 0
\end{cases}$$

**Base inicial:** $\{s_1,\, s_2,\, a_3\}$

> ¿Por qué la base inicial incluye $a_3$ en lugar de $e_3$? Razone antes de continuar.

### Tableau Inicial (Iteración 0)

El sistema completo $[A \mid \cdots]$ en términos de columnas por variable:

$$[A \mid \cdots] = \begin{bmatrix} 1 & 1 & 1 & 0 & 0 & 0 \\ 2 & 1 & 0 & 1 & 0 & 0 \\ 1 & 0 & 0 & 0 & -1 & 1 \end{bmatrix} \begin{matrix} \leftarrow x_1,\,x_2,\,s_1,\,s_2,\,e_3,\,a_3 \end{matrix}$$

**Recuerde:** la fila CR inicial tiene $-c_j$ para cada variable no básica, y el coeficiente de la artificial $a_3$ en la fila CR es $+M$ (ya que $c_{a_3} = -M$ y CR muestra el negativo). Como $a_3$ es básica, su entrada en CR debe ser $0$: aplique $\text{CR}_{\text{nuevo}} = \text{CR}^{(0)} - M \cdot R_{a_3}$.

Complete el tableau inicial:

| Base | $x_1$ | $x_2$ | $s_1$ | $s_2$ | $e_3$ | $a_3$ | RHS |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| **CR** | | | | | | | |
| $s_1$ | | | | | | | |
| $s_2$ | | | | | | | |
| $a_3$ | | | | | | | |

**Criterio de entrada:** ¿cuál es el costo reducido más negativo? ¿Qué variable entra?

Variable que entra: __________

**Prueba del cociente** (solo filas con coeficiente positivo en la columna de entrada):

| Fila | $b_i$ | $a_{i,\text{entrada}}$ | Cociente |
|:---:|:---:|:---:|:---:|
| $s_1$ | | | |
| $s_2$ | | | |
| $a_3$ | | | |

Variable que sale: __________ | Elemento pivote: __________

### Iteración 1

Aplique las operaciones de fila usando el pivote identificado en la iteración anterior. Muestre las operaciones explícitamente:

$$R_{\text{nueva fila pivote}} = \frac{R_{\text{pivote}}}{\text{elemento pivote}}$$

$$R_{\text{CR}}^{\text{nuevo}} = R_{\text{CR}} - (\text{CR}_{\text{col entrada}}) \cdot R_{\text{nueva fila pivote}}$$

$$R_{\text{otras filas}}^{\text{nuevo}} = R_{\text{original}} - (\text{coef. col entrada}) \cdot R_{\text{nueva fila pivote}}$$

| Base | $x_1$ | $x_2$ | $s_1$ | $s_2$ | $e_3$ | $a_3$ | RHS |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| **CR** | | | | | | | |
| | | | | | | | |
| | | | | | | | |
| | | | | | | | |

Solución parcial: $x_1 = \_\_,\; z = \_\_$. ¿Salió la artificial de la base? ___

**Criterio de entrada:** ¿cuál es el costo reducido más negativo? Variable que entra: __________

**Prueba del cociente:**

| Fila | $b_i$ | $a_{i,\text{entrada}}$ | Cociente |
|:---:|:---:|:---:|:---:|
| | | | |
| | | | |
| | | | |

Variable que sale: __________ | Elemento pivote: __________

### Iteración 2 — Solución Óptima

Aplique nuevamente las operaciones de fila:

| Base | $x_1$ | $x_2$ | $s_1$ | $s_2$ | $e_3$ | $a_3$ | RHS |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| **CR** | | | | | | | |
| | | | | | | | |
| | | | | | | | |
| | | | | | | | |

¿Se cumple la condición de optimalidad? _____ ¿Por qué? _______________________________

**Solución óptima:**

$$x_1^* = \_\_\_\_, \quad x_2^* = \_\_\_\_, \quad z^* = \_\_\_\_$$

**Interpretación:** ¿qué significan los valores de $s_1$, $s_2$, $e_3$ en términos del negocio?

- $s_1 = \_\_$: _______________________________________________
- $s_2 = \_\_$: _______________________________________________
- $e_3 = \_\_$: _______________________________________________

---

## 3. Mismo Ejercicio: Simplex Matricial

Aplicamos el método matricial al mismo problema. Recordar las fórmulas clave:

| Fórmula | Descripción |
|:---|:---|
| $c_B B^{-1} A_{NB} - c_{NB}$ | Costos reducidos de las variables no básicas |
| $B^{-1} a_k$ | Columna actualizada de la variable $k$ que entra |
| $B^{-1} b$ | Valores actuales de las variables básicas (RHS) |
| $c_B B^{-1} b$ | Valor actual de la función objetivo |

### Sistema completo $[A \mid \cdots]$

Las columnas del sistema completo (variables $x_1, x_2, s_1, s_2, e_3, a_3$) son:

$$\begin{array}{ccccccc}
& x_1 & x_2 & s_1 & s_2 & e_3 & a_3 \\
[A|\cdots] = & \begin{bmatrix}1\\2\\1\end{bmatrix} & \begin{bmatrix}1\\1\\0\end{bmatrix} & \begin{bmatrix}1\\0\\0\end{bmatrix} & \begin{bmatrix}0\\1\\0\end{bmatrix} & \begin{bmatrix}0\\0\\-1\end{bmatrix} & \begin{bmatrix}0\\0\\1\end{bmatrix}
\end{array}$$

**Nota:** la base inicial $\{s_1, s_2, a_3\}$ incluye la variable artificial, que permite arrancar con $B = I_3$. El costo $c_{a_3} = -M$ fuerza la salida de $a_3$ en la primera iteración.

In [2]:
import numpy as np
from numpy.linalg import inv

# RHS del sistema
b = np.array([6, 10, 2], dtype=float)

# Columnas del sistema completo por variable
cols = {
    'x1': np.array([1, 2, 1], dtype=float),
    'x2': np.array([1, 1, 0], dtype=float),
    's1': np.array([1, 0, 0], dtype=float),
    's2': np.array([0, 1, 0], dtype=float),
    'e3': np.array([0, 0, -1], dtype=float),
    'a3': np.array([0, 0, 1], dtype=float),
}

# Gran M (valor numerico grande)
M = 1000

# Coeficientes en la funcion objetivo
c_obj = {'x1': 5, 'x2': 6, 's1': 0, 's2': 0, 'e3': 0, 'a3': -M}

### Iteración 0

**Base:** $\{s_1,\, s_2,\, a_3\}$ — variables no básicas: $\{x_1,\, x_2,\, e_3\}$

**Paso 1 — Construir $B$ y $c_B$**

| Variable | Columna en $[A \mid \cdots]$ |
|:---:|:---:|
| $s_1$ | $[\;,\;,\;]^\top$ |
| $s_2$ | $[\;,\;,\;]^\top$ |
| $a_3$ | $[\;,\;,\;]^\top$ |

$$B = \begin{bmatrix} & & \\ & & \\ & & \end{bmatrix} \qquad c_B = [\quad,\quad,\quad]$$

**Paso 2 — Calcular $B^{-1}$**

$$B^{-1} = \begin{bmatrix} & & \\ & & \\ & & \end{bmatrix}$$

**Paso 3 — Costos reducidos** (no básicas: $x_1, x_2, e_3$)

$$\bar{c} = c_B B^{-1} A_{NB} - c_{NB} = [\quad,\quad,\quad]$$

Variable que entra: __________ (costo reducido más negativo: ______)

**Paso 4 — Prueba del cociente**

Columna de la variable que entra: $B^{-1} a_k = [\quad,\quad,\quad]^\top$

| Base | $B^{-1}b$ | $B^{-1}a_k$ | Cociente |
|:---:|:---:|:---:|:---:|
| $s_1$ | | | |
| $s_2$ | | | |
| $a_3$ | | | |

Variable que sale: __________  $\Rightarrow$  Nueva base: $\{\quad,\quad,\quad\}$

In [14]:
import numpy as np 
# --- Iteracion 0 ---
base    = ['s1', 's2', 'a3']
nonbase = ['x1', 'x2', 'e3']

#### CODIGO AQUI ####

B = np.array([[1,0,0],[0,1,0],[0,0,1]])
A = np.array([[1,1,0],[2,1,0],[1,0,-1]])
c = np.array([5,6,0])
c_b = np.array([0,0,-M])
b = np.array([6,10,2])

# c_b * B^-1 * A - c

B_inv = np.linalg.inv(B)

cost = c_b@B_inv@A - c
print(cost)


#####################

print (B_inv@b)
print(B_inv@A)

# Entra x_1 y sale a_3

# --- Iteracion 1 ---
base    = ['s1', 's2', 'x1']
nonbase = ['a3', 'x2', 'e3']

#### CODIGO AQUI ####

B = np.array([[1,0,1],[0,1,2],[0,0,1]])
A = np.array([[0,1,0],[0,1,0],[1,0,-1]])
c = np.array([-M,6,0])
c_b = np.array([0,0,5])
b = np.array([6,10,2])

# c_b * B^-1 * A - c

B_inv = np.linalg.inv(B)

cost = c_b@B_inv@A - c
print(cost)


#####################
print("Iteracion 1")

print (B_inv@b)
print(cost)

print("\n",B_inv@A)

# Entra x2 y sale s1


base    = ['x1', 's2', 'x1']
nonbase = ['a3', 's1', 'e3']

#### CODIGO AQUI ####

B = np.array([[1,0,1],[1,1,2],[0,0,1]])
A = np.array([[0,1,0],[0,0,0],[1,0,-1]])
c = np.array([-M,0,0])
c_b = np.array([6,0,5])
b = np.array([6,10,2])

# c_b * B^-1 * A - c

B_inv = np.linalg.inv(B)

cost = c_b@B_inv@A - c
print(cost)


#####################
print("Iteracion 1")

print (B_inv@b)
print(cost)

print("\n",B_inv@A)
print(c_b@B_inv@b)

[-1005.    -6.  1000.]
[ 6. 10.  2.]
[[ 1.  1.  0.]
 [ 2.  1.  0.]
 [ 1.  0. -1.]]
[1005.   -6.   -5.]
Iteracion 1
[4. 6. 2.]
[1005.   -6.   -5.]

 [[-1.  1.  1.]
 [-2.  1.  2.]
 [ 1.  0. -1.]]
[999.   6.   1.]
Iteracion 1
[4. 2. 2.]
[999.   6.   1.]

 [[-1.  1.  1.]
 [-1. -1.  1.]
 [ 1.  0. -1.]]
34.0


### Iteración 1

Actualice la base según el resultado de la iteración anterior.

**Paso 1 — Construir $B$ y $c_B$**

| Variable | Columna en $[A \mid \cdots]$ |
|:---:|:---:|
| $\_\_$ | $[\;,\;,\;]^\top$ |
| $\_\_$ | $[\;,\;,\;]^\top$ |
| $\_\_$ | $[\;,\;,\;]^\top$ |

$$B = \begin{bmatrix} & & \\ & & \\ & & \end{bmatrix} \qquad c_B = [\quad,\quad,\quad]$$

**Paso 2 — Calcular $B^{-1}$**

$$B^{-1} = \begin{bmatrix} & & \\ & & \\ & & \end{bmatrix}$$

**Paso 3 — Costos reducidos** (identifique las no básicas)

$$B^{-1}b = [\quad,\quad,\quad]^\top \qquad z = \_\_\_\_$$

$$\bar{c} = c_B B^{-1} A_{NB} - c_{NB} = [\quad,\quad,\quad]$$

Variable que entra: __________ (costo reducido más negativo: ______)

**Paso 4 — Prueba del cociente**

Columna de la variable que entra: $B^{-1} a_k = [\quad,\quad,\quad]^\top$

| Base | $B^{-1}b$ | $B^{-1}a_k$ | Cociente |
|:---:|:---:|:---:|:---:|
| | | | |
| | | | |
| | | | |

Variable que sale: __________  $\Rightarrow$  Nueva base: $\{\quad,\quad,\quad\}$

In [4]:
# --- Iteracion 1 ---
# base    = [...]
# nonbase = [...]

#### CODIGO AQUI ####

#####################

### Iteración 2 — Verificar Optimalidad

Actualice la base según el resultado de la iteración anterior.

**Paso 1 — Construir $B$ y $c_B$**

| Variable | Columna en $[A \mid \cdots]$ |
|:---:|:---:|
| $\_\_$ | $[\;,\;,\;]^\top$ |
| $\_\_$ | $[\;,\;,\;]^\top$ |
| $\_\_$ | $[\;,\;,\;]^\top$ |

$$B = \begin{bmatrix} & & \\ & & \\ & & \end{bmatrix} \qquad c_B = [\quad,\quad,\quad]$$

**Paso 2 — Calcular $B^{-1}$**

$$B^{-1} = \begin{bmatrix} & & \\ & & \\ & & \end{bmatrix}$$

**Paso 3 — Costos reducidos y solución**

$$B^{-1}b = [\quad,\quad,\quad]^\top \quad \Rightarrow \quad \_\_=\_\_, \quad \_\_=\_\_, \quad \_\_=\_\_$$

$$z^* = c_B \cdot B^{-1}b = \_\_\_\_$$

$$\bar{c} = c_B B^{-1} A_{NB} - c_{NB} = [\quad,\quad,\quad]$$

¿Se cumple la condición de optimalidad? _____ ¿Por qué? ______________________________

$$\boxed{x_1^* = \_\_\_\_, \quad x_2^* = \_\_\_\_, \quad z^* = \_\_\_\_}$$

In [5]:
# --- Iteracion 2 ---
# base    = [...]
# nonbase = [...]

#### CODIGO AQUI ####

#####################

---

## 4. Verificación Computacional

### 4.1 Solución con `scipy.optimize.linprog`

`linprog` minimiza, por lo que se niega la función objetivo. La restricción $\geq$ se convierte a $\leq$ multiplicando por $-1$:

$$x_1 \geq 2 \quad \Leftrightarrow \quad -x_1 \leq -2$$

Complete el código para verificar la solución obtenida manualmente:

In [6]:
from scipy.optimize import linprog

# linprog minimiza: negar la funcion objetivo para maximizar
# c_scipy = [...]

# A_ub @ x <= b_ub  (incluir las 3 restricciones; la >= se convierte)
# A_ub = [...]
# b_ub = [...]

# bounds = [...]

#### CODIGO AQUI ####

#####################

### 4.2 Solución con `gurobipy`

In [7]:
import gurobipy as gp
from gurobipy import GRB

# Crear modelo, agregar variables, funcion objetivo y restricciones
# Recuerde: la restriccion de contrato minimo es x1 >= 2

#### CODIGO AQUI ####

#####################

### 4.3 Comparación de Métodos

Complete la tabla con los resultados obtenidos:

| Método | $x_1^*$ | $x_2^*$ | $z^*$ |
|:---|:---:|:---:|:---:|
| Simplex Tableau (Gran M) | | | |
| Simplex Matricial (Gran M) | | | |
| `scipy.optimize.linprog` | | | |
| `gurobipy` | | | |

**Conclusión del análisis:** (completar)

- ¿Qué restricciones están activas en el óptimo y qué implica eso para el negocio?
- ¿Qué pasaría si el contrato mínimo exigiera 5 paneles estándar en lugar de 2?